services:
  chatgpt-next-web:
    build:
      context: .
      dockerfile: Dockerfile
    image: iflytek-chat:local

  chatgpt-next-web-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    image: iflytek-chat:local
